# -*- coding: utf-8 -*-
"""Deployment of Skin Cancer model on Streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s1IzE-nyy1B7w9ZTtYoR2bQXNii8E-lw
"""

!pip install streamlit

!pip install pyngrok==4.1.1

# Commented out IPython magic to ensure Python compatibility.
# %%writefile skin_cancer.py
# import streamlit as st
# import numpy as np
# import tensorflow as tf
# 
# #st.set_option('deprecation.showfileUploaderEncoding', False)
# @st.cache(allow_output_mutation = True)
# 
# def load_model():
#   model = tf.keras.models.load_model("/content/drive/MyDrive/skin_cancer/skin_cancer_model_vgg19.h5")
#   return model
# 
# model = load_model()
# st.write("Skin Cancer Classification")
# 
# file= st.file_uploader("Please upload an skin cancer image", type = ['jpg', 'png'])
# from PIL import Image, ImageOps
# 
# def import_and_predict(image_data, model):
#   size = (224, 224)
#   image = ImageOps.fit(image_data, size, Image.ANTIALIAS)
#   img = np.asarray(image) 
#   img = img/255.0
#   img_reshape = img[np.newaxis,...]
#   prediction = model.predict(img_reshape)
# 
#   return prediction
# 
# if file is None:
#   st.text("Please upload an image file...")
# 
# else:
#   image = Image.open(file)
#   st.image(image, use_column_width = True)
#   predictions = import_and_predict(image, model)
#   class_names = ["Benign", "Malignant"]
#   if np.argmax(predictions) == 0:
#     st.write("Great!!! You don't have Skin Cancer")
#   else:
#     st.write("Sorry, you have skin cancer disease kindly contact your doctor.")

#!ngrok authtoken XXXXXXXXXXXXXXXXX 

!nohup streamlit run skin_cancer.py &

from pyngrok import ngrok
public_url = ngrok.connect(port = '8501')

public_url

#!streamlit run skin_cancer.py &>/dev/null

!cat /content/nohup.out

#ngrok.kill()



